### ISSUE TITLE
Not working in Umbraco 17.5.0

### ISSUE THREAD

**Issue by russellshome** [nul800sebastiaan/Cultiv.Hangfire#57]
In Settings, selecting Hangfire displas nothing and there is a javascript error in the console

view.controller.ts:136 Uncaught (in promise) TypeError: t.provideContext is not a function
    at s.provideAt (view.controller.ts:136:39)
    at Object.setup (section-main-views.element.ts:128:15)
    at _t (router.ts:165:15)
    at async kt.renderPath (router-slot.ts:441:19)
    at async kt.render (router-slot.ts:257:3)

It works fine in the previous version 17.4.2 but fails in 17.5.0

**Comment by Stanislaw-Rudnicki** [comment]
@nul800sebastiaan 
I'm experiencing the same problem. Looking forward to a fix.

**Comment by warrenbuckley** [comment]
> [!NOTE]
> Findings/summary found with Claude

Confirmed root cause — this is a real breaking change in Umbraco 17.5.0.

**What changed:** core commit [`d40c959`](https://github.com/umbraco/Umbraco-CMS/commit/d40c959be7f8f95140492ce6c9105be264758f64) ("Dashboard: Browser title + Hints", [umbraco/Umbraco-CMS#22517](https://github.com/umbraco/Umbraco-CMS/pull/22517)), shipped in 17.5.0, makes `UmbSectionMainViewElement`'s route `setup()` unconditionally call `context.provideAt(component)` on every dashboard/section-view element instance (to wire up the new browser-title/hints `UMB_VIEW_CONTEXT`). That call does `controllerHost.provideContext(...)` on your element (`view.controller.ts:136`), which requires the element to implement Umbraco's `UmbControllerHost`/context-API surface. This applies identically to both the `"dashboard"` and `"sectionView"` extension types — the change touches both route builders in the same commit, so switching extension types wouldn't avoid it.

`dashboard-element.js` currently extends plain `HTMLElement`:
```js
export default class CultivHangfireDashboardElement extends HTMLElement {
```
That mixin was intentionally dropped in [`948030b`](https://github.com/nul800sebastiaan/Cultiv.Hangfire/commit/948030b679dc55ece80d7dee12c5d4667c9331c0) ("Not using anything related to Umbraco here, so just extend regular `HTMLElement`") back when nothing in the element consumed Umbraco context — reasonable at the time, but 17.5.0 now requires every dashboard/section-view element to have `provideContext` regardless of whether it uses context itself. Note this requirement isn't enforced by Umbraco's TypeScript types (`UmbDashboardElement` just requires `extends HTMLElement`), so it's an easy one to get bitten by silently.

**Fix:** restore what the element had before [`948030b`](https://github.com/nul800sebastiaan/Cultiv.Hangfire/commit/948030b679dc55ece80d7dee12c5d4667c9331c0) — wrap it in `UmbElementMixin`:
```js
import { UmbElementMixin } from '@umbraco-cms/backoffice/element-api';
...
export default class CultivHangfireDashboardElement extends UmbElementMixin(HTMLElement) {
```
That's the only change needed; confirmed working locally against 17.5.0.

**Comment by nul800sebastiaan** [comment]
Fixed in 5.5.3, now on NuGet: https://www.nuget.org/packages/Cultiv.Hangfire/5.5.3

**Comment by nul800sebastiaan** [comment]
Just to update, on v18 I also needed to update the auth method. It stays the same as it was on v17, but [release 5.5.4](https://github.com/nul800sebastiaan/Cultiv.Hangfire/releases/tag/v5.5.4) fixes that and a few more small issues.
